/**
 * An HTML fragment rendered through Svelte's `{@html}` boundary.
 *
 * Values of this type must come from the escaping Rust renderer or from trusted,
 * source-controlled documentation. It is a documentation marker, not runtime sanitization.
 */
export type QApiTrustedHtml = string;

export interface QApiEntry {
  name: string;
  /** Escaped HTML generated by the Rust docgen renderer. */
  header: QApiTrustedHtml;
  /** Trusted, source-controlled JSDoc that may intentionally contain HTML. */
  description: QApiTrustedHtml;
}

export interface QApiGeneric {
  name: string;
  /** An escaped HTML fragment generated by the Rust docgen renderer. */
  constraint?: QApiTrustedHtml;
  /** An escaped HTML fragment generated by the Rust docgen renderer. */
  default?: QApiTrustedHtml;
}

export interface QComponentDocs {
  name: string;
  description: string;
  docs: {
    generics: QApiGeneric[];
    /** An escaped HTML fragment generated by the Rust docgen renderer. */
    domAttributesConstraint: QApiTrustedHtml | undefined;
    props: QApiEntry[];
    snippets: QApiEntry[];
    methods: (QApiEntry | QComponentMethod)[];
    events: QComponentEvent[];
    /** Complete, self-contained TypeScript definitions keyed by the referenced type name. */
    typeDependencies: Record<string, string>;
  };
}

export interface QComponentType {
  name: string;
  description: string;
}

export interface QComponentEvent {
  name: string;
  type: string;
  /** Trusted, source-controlled documentation that may intentionally contain HTML. */
  description: QApiTrustedHtml;
}

export interface QComponentMethod {
  name: string;
  type: string;
  /** Trusted, source-controlled documentation that may intentionally contain HTML. */
  description: QApiTrustedHtml;
}
