export const QIconDocsProps = [
  {
    name: "size",
    type: "QIconSizeOptions",
    optional: true,
    clickableType: true,
    description:
      'The size of the icon. Can be specified with CSS units. If no unit is specified, "px" will be used.',
    default: "md",
  },
  {
    name: "type",
    type: "QIconTypeOptions",
    optional: true,
    clickableType: true,
    description: "The type of the icon.",
    default: "outlined",
  },
  {
    name: "name",
    type: "string",
    optional: true,
    clickableType: false,
    description: "The name of the Material Symbols icon.",
    default: "undefined",
  },
  {
    name: "filled",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Determines whether the icon should be filled.",
    default: "false",
  },
  {
    name: "svg",
    type: "string",
    optional: true,
    clickableType: false,
    description: "The SVG content for the icon.",
    default: "undefined",
  },
  {
    name: "img",
    type: "string",
    optional: true,
    clickableType: false,
    description: "The image source for the icon.",
    default: "undefined",
  },
  {
    name: "imgAttributes",
    type: "Record<string, any>",
    optional: true,
    clickableType: true,
    description:
      'Additional attributes for the image element when using the `img` prop, as for example the "alt" attribute.',
    default: "{}",
  },
  {
    name: "color",
    type: "string",
    optional: true,
    clickableType: false,
    description: "The color of the icon.",
    default: "undefined",
  },
];
