export const QIconDocsProps = [
  {
    name: "size",
    type: '"xs" | "sm" | "md" | "lg" | "xl" | string | number',
    optional: false,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "type",
    type: '"outlined" | "sharp" | "rounded"',
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "name",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "fill",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "svg",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "img",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "imgAttributes",
    type: "Record<string, any>",
    optional: false,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "color",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];
