export const Components = {
  QAvatar: "QAvatar",
  QBreadcrumbs: "QBreadcrumbs",
  QBreadcrumbsEl: "QBreadcrumbsEl",
  QBtn: "QBtn",
  QIconBtn: "QIconBtn",
  QCard: "QCard",
  QCardSection: "QCardSection",
  QCardActions: "QCardActions",
  QCheckbox: "QCheckbox",
  QChip: "QChip",
  QCircularProgress: "QCircularProgress",
  QCodeBlock: "QCodeBlock",
  QDialog: "QDialog",
  QDrawer: "QDrawer",
  QExpansionItem: "QExpansionItem",
  QFooter: "QFooter",
  QHeader: "QHeader",
  QHeaderTitle: "QHeaderTitle",
  QIcon: "QIcon",
  QInput: "QInput",
  QSelect: "QSelect",
  QSnackbar: "QSnackbar",
  QLayout: "QLayout",
  QList: "QList",
  QItem: "QItem",
  QItemSection: "QItemSection",
  QLinearProgress: "QLinearProgress",
  QMenu: "QMenu",
  QRadio: "QRadio",
  QRailbar: "QRailbar",
  QSeparator: "QSeparator",
  QTabs: "QTabs",
  QTab: "QTab",
  QTable: "QTable",
  QSwitch: "QSwitch",
  QTooltip: "QTooltip",
} as const;

export const ComponentPaths = {
  Avatar: "avatar",
  Breadcrumbs: "breadcrumbs",
  Button: "button",
  Card: "card",
  Checkbox: "checkbox",
  Chip: "chip",
  CodeBlock: "codeBlock",
  Dialog: "dialog",
  Drawer: "drawer",
  ExpansionItem: "expansion-item",
  Footer: "footer",
  Header: "header",
  Icon: "icon",
  Input: "input",
  Layout: "layout",
  List: "list",
  Menu: "menu",
  Progress: "progress",
  Radio: "radio",
  Railbar: "railbar",
  Select: "select",
  Snackbar: "snackbar",
  Separator: "separator",
  Switch: "switch",
  Table: "table",
  Tabs: "tabs",
  Tooltip: "tooltip",
} as const;

export const ComponentCss = {
  Avatar: "components/avatar",
  Breadcrumbs: "components/breadcrumbs",
  Button: "components/button",
  Card: "components/card",
  Checkbox: "components/checkbox",
  Chip: "components/chip",
  Dialog: "components/dialog",
  Drawer: "components/drawer",
  ExpansionItem: "components/expansion-item",
  Field: "shared/field",
  Footer: "components/footer",
  Header: "components/header",
  Icon: "components/icon",
  Input: "components/input",
  Layout: "components/layout",
  List: "components/list",
  Menu: "components/menu",
  Progress: "components/progress",
  Radio: "components/radio",
  Railbar: "components/railbar",
  Select: "components/select",
  Snackbar: "components/snackbar",
  Separator: "components/separator",
  Switch: "components/switch",
  Table: "components/table",
  Tabs: "components/tabs",
  Tooltip: "components/tooltip",
} as const;

export type ComponentCssName = (typeof ComponentCss)[keyof typeof ComponentCss];

const buttonCss = [ComponentCss.Button, ComponentCss.Icon, ComponentCss.Progress];
const chipCss = [ComponentCss.Chip, ComponentCss.Avatar, ComponentCss.Icon];
const expansionItemCss = [
  ComponentCss.ExpansionItem,
  ComponentCss.Button,
  ComponentCss.Icon,
  ComponentCss.List,
  ComponentCss.Progress,
];
const fieldCss = [ComponentCss.Field];
const selectCss = [
  ComponentCss.Field,
  ComponentCss.Select,
  ComponentCss.Icon,
  ComponentCss.List,
  ComponentCss.Menu,
];
const snackbarCss = [ComponentCss.Snackbar, ...buttonCss];
const switchCss = [ComponentCss.Switch, ComponentCss.Icon];
const tabsCss = [ComponentCss.Tabs, ComponentCss.Icon];
const tableCss = [ComponentCss.Table, ...buttonCss, ...selectCss];

export const ComponentCssDependencies = {
  [Components.QAvatar]: [ComponentCss.Avatar],
  [Components.QBreadcrumbs]: [ComponentCss.Breadcrumbs],
  [Components.QBreadcrumbsEl]: [ComponentCss.Breadcrumbs, ComponentCss.Icon],
  [Components.QBtn]: buttonCss,
  [Components.QIconBtn]: buttonCss,
  [Components.QCard]: [ComponentCss.Card],
  [Components.QCardSection]: [ComponentCss.Card],
  [Components.QCardActions]: [ComponentCss.Card],
  [Components.QCheckbox]: [ComponentCss.Checkbox],
  [Components.QChip]: chipCss,
  [Components.QCircularProgress]: [ComponentCss.Progress],
  [Components.QCodeBlock]: buttonCss,
  [Components.QDialog]: [ComponentCss.Dialog],
  [Components.QDrawer]: [ComponentCss.Drawer],
  [Components.QExpansionItem]: expansionItemCss,
  [Components.QFooter]: [ComponentCss.Footer],
  [Components.QHeader]: [ComponentCss.Header],
  [Components.QHeaderTitle]: [ComponentCss.Header],
  [Components.QIcon]: [ComponentCss.Icon],
  [Components.QInput]: fieldCss,
  [Components.QSelect]: selectCss,
  [Components.QSnackbar]: snackbarCss,
  [Components.QLayout]: [ComponentCss.Layout],
  [Components.QList]: [ComponentCss.List],
  [Components.QItem]: [ComponentCss.List],
  [Components.QItemSection]: [ComponentCss.List],
  [Components.QLinearProgress]: [ComponentCss.Progress],
  [Components.QMenu]: [ComponentCss.Menu],
  [Components.QRadio]: [ComponentCss.Radio],
  [Components.QRailbar]: [ComponentCss.Railbar],
  [Components.QSeparator]: [ComponentCss.Separator],
  [Components.QTabs]: [ComponentCss.Tabs],
  [Components.QTab]: tabsCss,
  [Components.QTable]: tableCss,
  [Components.QSwitch]: switchCss,
  [Components.QTooltip]: [ComponentCss.Tooltip],
} satisfies Record<(typeof Components)[keyof typeof Components], readonly ComponentCssName[]>;

export const ComponentPathCssDependencies = {
  [ComponentPaths.Avatar]: [ComponentCss.Avatar],
  [ComponentPaths.Breadcrumbs]: [ComponentCss.Breadcrumbs, ComponentCss.Icon],
  [ComponentPaths.Button]: buttonCss,
  [ComponentPaths.Card]: [ComponentCss.Card],
  [ComponentPaths.Checkbox]: [ComponentCss.Checkbox],
  [ComponentPaths.Chip]: chipCss,
  [ComponentPaths.CodeBlock]: buttonCss,
  [ComponentPaths.Dialog]: [ComponentCss.Dialog],
  [ComponentPaths.Drawer]: [ComponentCss.Drawer],
  [ComponentPaths.ExpansionItem]: expansionItemCss,
  [ComponentPaths.Footer]: [ComponentCss.Footer],
  [ComponentPaths.Header]: [ComponentCss.Header],
  [ComponentPaths.Icon]: [ComponentCss.Icon],
  [ComponentPaths.Input]: fieldCss,
  [ComponentPaths.Layout]: [ComponentCss.Layout],
  [ComponentPaths.List]: [ComponentCss.List],
  [ComponentPaths.Menu]: [ComponentCss.Menu],
  [ComponentPaths.Progress]: [ComponentCss.Progress],
  [ComponentPaths.Radio]: [ComponentCss.Radio],
  [ComponentPaths.Railbar]: [ComponentCss.Railbar],
  [ComponentPaths.Select]: selectCss,
  [ComponentPaths.Snackbar]: snackbarCss,
  [ComponentPaths.Separator]: [ComponentCss.Separator],
  [ComponentPaths.Switch]: switchCss,
  [ComponentPaths.Table]: tableCss,
  [ComponentPaths.Tabs]: tabsCss,
  [ComponentPaths.Tooltip]: [ComponentCss.Tooltip],
} satisfies Record<
  (typeof ComponentPaths)[keyof typeof ComponentPaths],
  readonly ComponentCssName[]
>;

export const UtilityCssDependencies = {
  Notify: snackbarCss,
} satisfies Record<string, readonly ComponentCssName[]>;
