export const QSeparatorPropsVertical = [
  {
    name: "spacing",
    type: "QuaffSizes",
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "inset",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "vertical",
    type: "true",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "color",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "size",
    type: "string",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "text",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "textAlign",
    type: '"top" | "middle" | "bottom"',
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];

export const QSeparatorPropsHorizontal = [
  {
    name: "spacing",
    type: "QuaffSizes",
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "inset",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "vertical",
    type: "false",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "color",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "size",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "text",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "textAlign",
    type: '"left" | "center" | "right"',
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];
