export const QTableDocsProps = [
  {
    name: "columns",
    type: "QTableColumn[]",
    optional: false,
    clickableType: true,
    description: "Column definitions of the table.",
    default: "[]",
  },
  {
    name: "rows",
    type: "QTableRow[]",
    optional: false,
    clickableType: true,
    description: "Rows of the table.",
    default: "[]",
  },
  {
    name: "flat",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Uses flat design, removing the box-shadow around the table.",
    default: "false",
  },
  {
    name: "bordered",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Adds a border around the table.",
    default: "false",
  },
  {
    name: "dense",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Shows the Table in dense mode (takes up less space).",
    default: "false",
  },
];
