export const QBtnDocsProps = [
  {
    name: "disable",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Puts the button in a disabled state, making it unclickable.",
    default: "false",
  },
  {
    name: "flat",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Use flat design for the button, removing its elevation and background-color.",
    default: "false",
  },
  {
    name: "icon",
    type: "string",
    optional: true,
    clickableType: false,
    description: "Name of the leading icon to use for the button.",
    default: "undefined",
  },
  {
    name: "label",
    type: "string",
    optional: true,
    clickableType: false,
    description: "Text to use for the button.",
    default: "undefined",
  },
  {
    name: "loading",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Puts the button in a loading state, adding a loader as the leading icon.",
    default: "false",
  },
  {
    name: "outline",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Use outline design for the button, adding a border around it.",
    default: "false",
  },
  {
    name: "round",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Use round design for the button, adding a border-radius to it.",
    default: "true",
  },
  {
    name: "to",
    type: "string",
    optional: true,
    clickableType: false,
    description:
      'Makes the button navigational. Can be used with the router (e.g to="home") or as a normal href attribute (e.g to="#section-id").',
    default: "undefined",
  },
  {
    name: "unelevated",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Removes the button's elevation.",
    default: "false",
  },
  {
    name: "size",
    type: "QBtnSizeOptions",
    optional: true,
    clickableType: true,
    description: "Size of the button.",
    default: "md",
  },
];
