export const QToggleDocsProps = [
  {
    name: "value",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "label",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "leftLabel",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "icon",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "disable",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];
