export const QInputDocsProps = [
  {
    name: "dense",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "disable",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "error",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "errorMessage",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "filled",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "hint",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "label",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "outlined",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "rounded",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "value",
    type: "string",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
];
