export const QChipDocsProps = [
  {
    name: "content",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "icon",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "iconRight",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "disable",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "responsive",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "vertical",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "round",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "outlined",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "size",
    type: '"small" | "medium" | "large"',
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "tabindex",
    type: "string | number",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "href",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];
