export const QChipDocsProps = [
  {
    name: "content",
    type: "string",
    optional: true,
    clickableType: false,
    description: "The content inside the chip. Will overwrite the default slot.",
    default: "undefined",
  },
  {
    name: "icon",
    type: "string",
    optional: true,
    clickableType: false,
    description:
      'Name of the leading icon to use for the chip. If starts with "img:", will be used as an image src instead.',
    default: "undefined",
  },
  {
    name: "iconRight",
    type: "string",
    optional: true,
    clickableType: false,
    description:
      'Name of the trailing icon to use for the chip. If starts with "img:", will be used as an image src instead.',
    default: "undefined",
  },
  {
    name: "disable",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Puts the chip in a disabled state, making it unclickable.",
    default: "false",
  },
  {
    name: "responsive",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Makes leading and trailing images responsive, making them take more space.",
    default: "false",
  },
  {
    name: "vertical",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "If true, the chip will display its content vertically.",
    default: "false",
  },
  {
    name: "round",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Use round design for the chip, adding a large border-radius to it.",
    default: "false",
  },
  {
    name: "outlined",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Use outline design for the chip, adding a border around it.",
    default: "false",
  },
  {
    name: "size",
    type: "QChipSizeOptions",
    optional: true,
    clickableType: true,
    description: "Size of the chip.",
    default: "small",
  },
  {
    name: "tabindex",
    type: "number",
    optional: true,
    clickableType: false,
    description: "Tabindex of the chip.",
    default: "undefined",
  },
  {
    name: "href",
    type: "string",
    optional: true,
    clickableType: false,
    description:
      'Makes the chip navigational. Can be used with the router (e.g to="/home") or as a normal href attribute (e.g to="#section-id").',
    default: "undefined",
  },
];
