export const QSeparatorPropsVertical = [
  {
    name: "spacing",
    type: "QuaffSizes",
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "inset",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "vertical",
    type: "true",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "color",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "size",
    type: "string",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "text",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "textAlign",
    type: '"top" | "middle" | "bottom"',
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];

export const QSeparatorPropsHorizontal = [
  {
    name: "spacing",
    type: "QuaffSizes",
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "inset",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "vertical",
    type: "false",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "color",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "size",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "text",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "textAlign",
    type: '"left" | "center" | "right"',
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];

export const QListDocsProps = [
  {
    name: "bordered",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "roundedBorders",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "dense",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "separator",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "separatorOptions",
    type: 'QSeparatorProps["textAlign"]\n  };',
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "padding",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "tag",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
];

export const QItemDocsProps = [
  {
    name: "tag",
    type: "string",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "active",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "clickable",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "dense",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "noRipple",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "tabindex",
    type: 'HTMLAttributes<HTMLElement>["tabindex"]',
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "target",
    type: 'HTMLAnchorAttributes["target"]',
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
];

export const QItemSectionDocsProps = [
  {
    name: "type",
    type: "QItemSectionTypes",
    optional: true,
    clickableType: true,
    description: "",
    default: "",
  },
];
