export const QDrawerDocsProps = [
  {
    name: "value",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "side",
    type: '"left" | "right"',
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "width",
    type: "number | string",
    optional: false,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "breakpoint",
    type: "number",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "showIfAbove",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "behavior",
    type: '"default" | "desktop" | "mobile"',
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "bordered",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "elevated",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "overlay",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "persistent",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "noSwipeOpen",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "noSwipeClose",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "noSwipeBackdrop",
    type: "boolean",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
];
