export const QDrawerDocsProps = [
  {
    name: "value",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "The value indicating whether the drawer is visible or hidden.",
    default: "true",
  },
  {
    name: "side",
    type: "QDrawerSideOptions",
    optional: true,
    clickableType: true,
    description: "The side of the layout where the drawer is positioned.",
    default: '"left"',
  },
  {
    name: "width",
    type: "number | string",
    optional: true,
    clickableType: true,
    description:
      'The width of the drawer. Can be specified with a CSS unit. If no unit is specified, "px" will be used.',
    default: "300",
  },
  {
    name: "breakpoint",
    type: "number",
    optional: true,
    clickableType: false,
    description: "The breakpoint at which the drawer behavior changes. (not supported yet)",
    default: "1023",
  },
  {
    name: "showIfAbove",
    type: "boolean",
    optional: true,
    clickableType: false,
    description:
      "Determines whether the drawer should be shown if the viewport width is above the specified breakpoint. (not supported yet)",
    default: "false",
  },
  {
    name: "behavior",
    type: "QDrawerBehaviorOptions",
    optional: true,
    clickableType: true,
    description: "The behavior of the drawer based on the viewport width. (not supported yet)",
    default: '"default"',
  },
  {
    name: "bordered",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Determines whether the drawer has a border around it.",
    default: "false",
  },
  {
    name: "elevated",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Determines whether the drawer has an elevated effect. (not supported yet)",
    default: "false",
  },
  {
    name: "overlay",
    type: "boolean",
    optional: true,
    clickableType: false,
    description:
      "Determines whether the wrawer should behave like an overlay (opening above the content) or not (pushing the content while opening).",
    default: "false",
  },
  {
    name: "persistent",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Determines whether the drawer remains persistent, not closing on click outside.",
    default: "false",
  },
  {
    name: "noSwipeOpen",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Determines whether swipe gestures can open the drawer. (not supported yet)",
    default: "false",
  },
  {
    name: "noSwipeClose",
    type: "boolean",
    optional: true,
    clickableType: false,
    description: "Determines whether swipe gestures can close the drawer. (not supported yet)",
    default: "false",
  },
  {
    name: "noSwipeBackdrop",
    type: "boolean",
    optional: true,
    clickableType: false,
    description:
      "Determines whether swipe gestures on the backdrop can close the drawer. (not supported yet)",
    default: "false",
  },
];
