<script lang="ts">
  import { QCodeBlock } from "$lib";
  import { QDocs, QDocsSection } from "$docs";
  import { useMeta } from "$lib/meta";
  import { pageMeta } from "$docs/metadata";

  useMeta(
    pageMeta(
      "Asset Optimization",
      "Speed up SvelteKit apps with smaller CSS and font downloads. Quaff keeps the styles and icons you use and loads only the font files you choose."
    )
  );
</script>

<QDocs
  docName="Asset Optimization"
  docDescription="Help your app load faster by sending less CSS and smaller font files."
>
  {#snippet display()}
    <QCodeBlock language="ts" code="quaffAssets()" />
  {/snippet}

  {#snippet usage()}
    <QDocsSection title="Setup" noCode>
      {#snippet sectionDescription()}
        <p>
          Add <code>quaffAssets()</code> to your Vite plugins. It includes styles for the Quaff components
          you use, plus shared styles and helpers.
        </p>
      {/snippet}

      <QCodeBlock
        title="vite.config.ts"
        language="ts"
        code={`import { quaffAssets } from "@quaffui/quaff/plugins/assets";
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [quaffAssets(), sveltekit()],
});`}
        copiable
      />
      <p class="q-mt-md">
        Remove any <code>@quaffui/quaff/css/index.css</code> import from
        <code>src/routes/+layout.svelte</code> so the plugin can choose which styles to include.
      </p>
    </QDocsSection>

    <QDocsSection title="Remove Unused CSS" noCode>
      {#snippet sectionDescription()}
        <p>
          Enable <code>css.stripUnused</code> to remove unused shared styles and helpers. Used components
          keep all their styles.
        </p>
      {/snippet}

      <QCodeBlock
        language="ts"
        code={`quaffAssets({
  css: {
    stripUnused: true,
    safelist: ["text-primary", /^q-pa-/],
  },
});`}
        copiable
      />
      <p class="q-mt-md">
        <code>css.safelist</code> keeps classes the plugin cannot detect. For example,
        <code>{'class={"q-pa-" + size}'}</code> builds a class name at runtime;
        <code>/^q-pa-/</code>
        keeps every class starting with <code>q-pa-</code>.
      </p>
    </QDocsSection>

    <QDocsSection title="Choose Fonts and Icons" noCode>
      {#snippet sectionDescription()}
        <p>
          Configure <code>fonts</code> to reduce font downloads too. Projects generated by
          <code>create-quaff</code> already include Roboto and Material Symbols. For a manual setup,
          add <code>@fontsource/roboto</code> for Roboto and <code>material-symbols</code> for icons if
          those packages are missing.
        </p>
      {/snippet}

      <p class="q-my-md">
        Choose Roboto weights, character groups (<code>subsets</code>), and file formats. For
        Material Symbols, choose <code>outlined</code>, <code>rounded</code>, or <code>sharp</code>.
        Enable <code>fonts.icons.stripUnused</code> to remove unused icons from the font.
      </p>
      <QCodeBlock
        language="ts"
        code={`quaffAssets({
  fonts: {
    roboto: {
      weights: [400, 500, 700],
      subsets: ["latin", "latin-ext"],
      formats: ["woff2"],
    },
    icons: {
      styles: ["outlined"],
      stripUnused: true,
      safelist: ["bookmark"],
    },
  },
});`}
        copiable
      />
      <p class="q-mt-md">
        Remove existing Roboto imports and Material Symbols <code>@font-face</code> rules from your
        app's stylesheet so the original fonts are not loaded alongside the optimized ones. In
        projects generated by <code>create-quaff</code>, these are in
        <code>src/styles/app.scss</code> or <code>src/styles/app.css</code>.
      </p>
      <p class="q-mt-md">
        The plugin keeps icons detected in your source files, plus icons used by Quaff components.
        Add icon names received from an API or external package to
        <code>fonts.icons.safelist</code>, as shown with <code>bookmark</code> above.
      </p>
      <p class="q-mt-md">
        Include the character groups your content needs. When you enable <code>fonts</code>, omitted
        options default to Roboto weights 400/500/700, all character groups, WOFF2/WOFF, and all
        three icon styles. To supply your own fonts, set <code>roboto: false</code> or
        <code>icons: false</code> inside <code>fonts</code>.
      </p>
    </QDocsSection>

    <QDocsSection title="Components Outside src" noCode>
      {#snippet sectionDescription()}
        <p>
          The plugin checks <code>src</code> by default. Set <code>sourceDir</code> to a directory
          or an array of directories to scan, or use <code>include</code> to keep components used by code
          outside them:
        </p>
      {/snippet}

      <QCodeBlock language="ts" code={'quaffAssets({ include: ["QBtn", "Notify"] });'} copiable />
      <p class="q-my-md">
        To include all Quaff styles during development, use <code>{'css: { dev: "full" }'}</code>.
      </p>
    </QDocsSection>
  {/snippet}
</QDocs>
