export const QLayoutDocsProps = [
  {
    name: "view",
    type: '`${"l"|"h"}${"h"|"H"}${"r"|"h"} ${"l"|"L"}${"p"}${"r"|"R"} ${"l"|"f"}${"f"|"F"}${"r"|"f"}`,',
    optional: false,
    clickableType: true,
    description: "",
    default: "",
  },
  {
    name: "leftDrawerWidth",
    type: "string | number",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "rightDrawerWidth",
    type: "string | number",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "leftRailbarWidth",
    type: "string | number",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
  {
    name: "rightRailbarWidth",
    type: "string | number",
    optional: false,
    clickableType: false,
    description: "",
    default: "",
  },
];
