name: Code Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.36

      - name: Prep
        run: bun install --frozen-lockfile && bun run write-version && bun run docgen-props && bun run docgen-snippets

      - name: Run Type Check
        run: bun run check

      - name: Run Lint
        run: bun run lint
